/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Public API
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateCustomerRequest {
    'name': string;
    'customerType': string | null;
    'email': string | null;
    'phone': string | null;
    'address': string | null;
    'website': string | null;
    'industry': string | null;
    'status': string | null;
    'notes': string | null;
    'priceListId'?: string | null;
}
export interface CreateSalesOrderLineRequest {
    'productId': string;
    'quantity': number;
    'unitPrice': number;
    'discountPercent': number;
    'discountAmount': number;
    'dropShipSupplierId'?: string | null;
}
export interface CreateSalesOrderRequest {
    'customerId': string;
    'orderNumber': string | null;
    'status': string;
    'discountPercent': number;
    'lines': Array<CreateSalesOrderLineRequest>;
}
export interface CustomerResponse {
    'id': string;
    'accountId': string;
    'name': string;
    'customerType': string;
    'email': string | null;
    'phone': string | null;
    'address': string | null;
    'website': string | null;
    'industry': string | null;
    'status': string;
    'notes': string;
    'createdAt': string;
    'updatedAt': string;
    'priceListId'?: string | null;
}
export interface InventoryDashboardStats {
    'totalItems': number;
    'lowStockCount': number;
}
export interface InventoryItemResponse {
    'id': string;
    'accountId': string;
    'productId': string;
    'productName': string;
    'sku': string;
    'quantityOnHand': number;
    'reorderLevel': number;
    'unitPrice': number;
    'createdAt': string;
    'updatedAt': string;
}
export interface MeResponse {
    'accountId': string;
    'accountName': string;
    'authMethod': string;
    'scopes': Array<string> | null;
    'apiKeyId': string | null;
}
export interface PagedResultOfCustomerResponse {
    'items': Array<CustomerResponse>;
    'totalCount': number;
    'currentPage': number;
    'pageSize': number;
    'totalPages': number;
}
export interface PagedResultOfSalesOrderDto {
    'items': Array<SalesOrderDto>;
    'totalCount': number;
    'currentPage': number;
    'pageSize': number;
    'totalPages': number;
}
export interface SalesOrder {
    'accountId'?: string;
    'customerId'?: string;
    'orderNumber'?: string;
    'orderDate'?: string;
    'dueDate'?: string;
    'status'?: string;
    'totalAmount'?: number;
    'discountPercent'?: number;
    'lines'?: Array<SalesOrderLine>;
    'id'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface SalesOrderDetailDto {
    'id'?: string;
    'orderNumber'?: string;
    'customerId'?: string;
    'customerName'?: string;
    'orderDate'?: string;
    'status'?: string;
    'totalAmount'?: number;
    'discountPercent'?: number;
    'invoiceId'?: string | null;
    'invoiceNumber'?: string | null;
    'invoiceStatus'?: string | null;
    'invoiceAmountDue'?: number;
    'lines'?: Array<SalesOrderLineDto>;
}
export interface SalesOrderDto {
    'id'?: string;
    'orderNumber'?: string;
    'customerId'?: string;
    'customerName'?: string;
    'orderDate'?: string;
    'status'?: string;
    'totalAmount'?: number;
    'discountPercent'?: number;
    'lineCount'?: number;
    'invoiceId'?: string | null;
    'invoiceNumber'?: string | null;
    'invoiceStatus'?: string | null;
    'invoiceAmountDue'?: number;
}
export interface SalesOrderLine {
    'salesOrderId'?: string;
    'productId'?: string;
    'quantity'?: number;
    'unitPrice'?: number;
    'lineTotal'?: number;
    'taxRate'?: number;
    'taxAmount'?: number;
    'discountPercent'?: number;
    'discountAmount'?: number;
    'quantityShipped'?: number;
    'dropShipSupplierId'?: string | null;
    'id'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface SalesOrderLineDto {
    'id'?: string;
    'productId'?: string;
    'productName'?: string;
    'quantity'?: number;
    'unitPrice'?: number;
    'lineTotal'?: number;
    'discountPercent'?: number;
    'discountAmount'?: number;
    'quantityShipped'?: number;
    'dropShipSupplierId'?: string | null;
}
export interface UpdateCustomerRequest {
    'name': string | null;
    'customerType': string | null;
    'email': string | null;
    'phone': string | null;
    'address': string | null;
    'website': string | null;
    'industry': string | null;
    'status': string | null;
    'notes': string | null;
    'priceListId'?: string | null;
}
export interface UpdateOrderStatusRequest {
    'status': string;
}
export interface UpdateSalesOrderRequest {
    'customerId': string;
    'discountPercent': number;
    'lines': Array<CreateSalesOrderLineRequest>;
}

/**
 * CrmApi - axios parameter creator
 */
export const CrmApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateCustomerRequest} createCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer: async (accountId: string, createCustomerRequest: CreateCustomerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('createCustomer', 'accountId', accountId)
            // verify required parameter 'createCustomerRequest' is not null or undefined
            assertParamExists('createCustomer', 'createCustomerRequest', createCustomerRequest)
            const localVarPath = `/api/v1/accounts/{accountId}/crm/customers`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCustomerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCustomer: async (accountId: string, customerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('deleteCustomer', 'accountId', accountId)
            // verify required parameter 'customerId' is not null or undefined
            assertParamExists('deleteCustomer', 'customerId', customerId)
            const localVarPath = `/api/v1/accounts/{accountId}/crm/customers/{customerId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{customerId}', encodeURIComponent(String(customerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomer: async (accountId: string, customerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('getCustomer', 'accountId', accountId)
            // verify required parameter 'customerId' is not null or undefined
            assertParamExists('getCustomer', 'customerId', customerId)
            const localVarPath = `/api/v1/accounts/{accountId}/crm/customers/{customerId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{customerId}', encodeURIComponent(String(customerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers: async (accountId: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('listCustomers', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{accountId}/crm/customers`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {UpdateCustomerRequest} updateCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomer: async (accountId: string, customerId: string, updateCustomerRequest: UpdateCustomerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('updateCustomer', 'accountId', accountId)
            // verify required parameter 'customerId' is not null or undefined
            assertParamExists('updateCustomer', 'customerId', customerId)
            // verify required parameter 'updateCustomerRequest' is not null or undefined
            assertParamExists('updateCustomer', 'updateCustomerRequest', updateCustomerRequest)
            const localVarPath = `/api/v1/accounts/{accountId}/crm/customers/{customerId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{customerId}', encodeURIComponent(String(customerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCustomerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CrmApi - functional programming interface
 */
export const CrmApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CrmApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateCustomerRequest} createCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCustomer(accountId: string, createCustomerRequest: CreateCustomerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCustomer(accountId, createCustomerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrmApi.createCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCustomer(accountId, customerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrmApi.deleteCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomer(accountId, customerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrmApi.getCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCustomers(accountId: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfCustomerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCustomers(accountId, status, search, filter, page, pageSize, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrmApi.listCustomers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {UpdateCustomerRequest} updateCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCustomer(accountId: string, customerId: string, updateCustomerRequest: UpdateCustomerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCustomer(accountId, customerId, updateCustomerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrmApi.updateCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CrmApi - factory interface
 */
export const CrmApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CrmApiFp(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateCustomerRequest} createCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer(accountId: string, createCustomerRequest: CreateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse> {
            return localVarFp.createCustomer(accountId, createCustomerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCustomer(accountId, customerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse> {
            return localVarFp.getCustomer(accountId, customerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers(accountId: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): AxiosPromise<PagedResultOfCustomerResponse> {
            return localVarFp.listCustomers(accountId, status, search, filter, page, pageSize, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} customerId 
         * @param {UpdateCustomerRequest} updateCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomer(accountId: string, customerId: string, updateCustomerRequest: UpdateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse> {
            return localVarFp.updateCustomer(accountId, customerId, updateCustomerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CrmApi - interface
 */
export interface CrmApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {CreateCustomerRequest} createCustomerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCustomer(accountId: string, createCustomerRequest: CreateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} [status] 
     * @param {string} [search] 
     * @param {string} [filter] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCustomers(accountId: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): AxiosPromise<PagedResultOfCustomerResponse>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {UpdateCustomerRequest} updateCustomerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCustomer(accountId: string, customerId: string, updateCustomerRequest: UpdateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerResponse>;

}

/**
 * CrmApi - object-oriented interface
 */
export class CrmApi extends BaseAPI implements CrmApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {CreateCustomerRequest} createCustomerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCustomer(accountId: string, createCustomerRequest: CreateCustomerRequest, options?: RawAxiosRequestConfig) {
        return CrmApiFp(this.configuration).createCustomer(accountId, createCustomerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig) {
        return CrmApiFp(this.configuration).deleteCustomer(accountId, customerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCustomer(accountId: string, customerId: string, options?: RawAxiosRequestConfig) {
        return CrmApiFp(this.configuration).getCustomer(accountId, customerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} [status] 
     * @param {string} [search] 
     * @param {string} [filter] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCustomers(accountId: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig) {
        return CrmApiFp(this.configuration).listCustomers(accountId, status, search, filter, page, pageSize, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} customerId 
     * @param {UpdateCustomerRequest} updateCustomerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCustomer(accountId: string, customerId: string, updateCustomerRequest: UpdateCustomerRequest, options?: RawAxiosRequestConfig) {
        return CrmApiFp(this.configuration).updateCustomer(accountId, customerId, updateCustomerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * InventoryApi - axios parameter creator
 */
export const InventoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventoryDashboard: async (accountId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('getInventoryDashboard', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{accountId}/inventory/dashboard`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventoryItem: async (accountId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('getInventoryItem', 'accountId', accountId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getInventoryItem', 'id', id)
            const localVarPath = `/api/v1/accounts/{accountId}/inventory/items/{id}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInventoryItems: async (accountId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('listInventoryItems', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{accountId}/inventory/items`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InventoryApi - functional programming interface
 */
export const InventoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InventoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInventoryDashboard(accountId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryDashboardStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInventoryDashboard(accountId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryApi.getInventoryDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInventoryItem(accountId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryItemResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInventoryItem(accountId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryApi.getInventoryItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listInventoryItems(accountId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InventoryItemResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listInventoryItems(accountId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryApi.listInventoryItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InventoryApi - factory interface
 */
export const InventoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InventoryApiFp(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventoryDashboard(accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<InventoryDashboardStats> {
            return localVarFp.getInventoryDashboard(accountId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventoryItem(accountId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemResponse> {
            return localVarFp.getInventoryItem(accountId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInventoryItems(accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponse>> {
            return localVarFp.listInventoryItems(accountId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InventoryApi - interface
 */
export interface InventoryApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInventoryDashboard(accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<InventoryDashboardStats>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInventoryItem(accountId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemResponse>;

    /**
     * 
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listInventoryItems(accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponse>>;

}

/**
 * InventoryApi - object-oriented interface
 */
export class InventoryApi extends BaseAPI implements InventoryApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getInventoryDashboard(accountId: string, options?: RawAxiosRequestConfig) {
        return InventoryApiFp(this.configuration).getInventoryDashboard(accountId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getInventoryItem(accountId: string, id: string, options?: RawAxiosRequestConfig) {
        return InventoryApiFp(this.configuration).getInventoryItem(accountId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listInventoryItems(accountId: string, options?: RawAxiosRequestConfig) {
        return InventoryApiFp(this.configuration).listInventoryItems(accountId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MeApi - axios parameter creator
 */
export const MeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentContext: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeApi - functional programming interface
 */
export const MeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentContext(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentContext(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.getCurrentContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeApi - factory interface
 */
export const MeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentContext(options?: RawAxiosRequestConfig): AxiosPromise<MeResponse> {
            return localVarFp.getCurrentContext(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeApi - interface
 */
export interface MeApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentContext(options?: RawAxiosRequestConfig): AxiosPromise<MeResponse>;

}

/**
 * MeApi - object-oriented interface
 */
export class MeApi extends BaseAPI implements MeApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentContext(options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).getCurrentContext(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SalesApi - axios parameter creator
 */
export const SalesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateSalesOrderRequest} createSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSalesOrder: async (accountId: string, createSalesOrderRequest: CreateSalesOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('createSalesOrder', 'accountId', accountId)
            // verify required parameter 'createSalesOrderRequest' is not null or undefined
            assertParamExists('createSalesOrder', 'createSalesOrderRequest', createSalesOrderRequest)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSalesOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSalesOrder: async (accountId: string, orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('deleteSalesOrder', 'accountId', accountId)
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('deleteSalesOrder', 'orderId', orderId)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders/{orderId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{orderId}', encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSalesOrder: async (accountId: string, orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('getSalesOrder', 'accountId', accountId)
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('getSalesOrder', 'orderId', orderId)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders/{orderId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{orderId}', encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [customerId] 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSalesOrders: async (accountId: string, customerId?: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('listSalesOrders', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders`
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            if (customerId !== undefined) {
                localVarQueryParameter['customerId'] = customerId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateSalesOrderRequest} updateSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSalesOrder: async (accountId: string, orderId: string, updateSalesOrderRequest: UpdateSalesOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('updateSalesOrder', 'accountId', accountId)
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('updateSalesOrder', 'orderId', orderId)
            // verify required parameter 'updateSalesOrderRequest' is not null or undefined
            assertParamExists('updateSalesOrder', 'updateSalesOrderRequest', updateSalesOrderRequest)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders/{orderId}`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{orderId}', encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSalesOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateOrderStatusRequest} updateOrderStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSalesOrderStatus: async (accountId: string, orderId: string, updateOrderStatusRequest: UpdateOrderStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('updateSalesOrderStatus', 'accountId', accountId)
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('updateSalesOrderStatus', 'orderId', orderId)
            // verify required parameter 'updateOrderStatusRequest' is not null or undefined
            assertParamExists('updateSalesOrderStatus', 'updateOrderStatusRequest', updateOrderStatusRequest)
            const localVarPath = `/api/v1/accounts/{accountId}/sales/orders/{orderId}/status`
                .replace('{accountId}', encodeURIComponent(String(accountId)))
                .replace('{orderId}', encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOrderStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SalesApi - functional programming interface
 */
export const SalesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SalesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateSalesOrderRequest} createSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSalesOrder(accountId: string, createSalesOrderRequest: CreateSalesOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SalesOrder>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSalesOrder(accountId, createSalesOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.createSalesOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSalesOrder(accountId, orderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.deleteSalesOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SalesOrderDetailDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSalesOrder(accountId, orderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.getSalesOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [customerId] 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSalesOrders(accountId: string, customerId?: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSalesOrders(accountId, customerId, status, search, filter, page, pageSize, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.listSalesOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateSalesOrderRequest} updateSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSalesOrder(accountId: string, orderId: string, updateSalesOrderRequest: UpdateSalesOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SalesOrder>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSalesOrder(accountId, orderId, updateSalesOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.updateSalesOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateOrderStatusRequest} updateOrderStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSalesOrderStatus(accountId: string, orderId: string, updateOrderStatusRequest: UpdateOrderStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSalesOrderStatus(accountId, orderId, updateOrderStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesApi.updateSalesOrderStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SalesApi - factory interface
 */
export const SalesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SalesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} accountId 
         * @param {CreateSalesOrderRequest} createSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSalesOrder(accountId: string, createSalesOrderRequest: CreateSalesOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrder> {
            return localVarFp.createSalesOrder(accountId, createSalesOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSalesOrder(accountId, orderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrderDetailDto> {
            return localVarFp.getSalesOrder(accountId, orderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} [customerId] 
         * @param {string} [status] 
         * @param {string} [search] 
         * @param {string} [filter] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSalesOrders(accountId: string, customerId?: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): AxiosPromise<PagedResultOfSalesOrderDto> {
            return localVarFp.listSalesOrders(accountId, customerId, status, search, filter, page, pageSize, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateSalesOrderRequest} updateSalesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSalesOrder(accountId: string, orderId: string, updateSalesOrderRequest: UpdateSalesOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrder> {
            return localVarFp.updateSalesOrder(accountId, orderId, updateSalesOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} accountId 
         * @param {string} orderId 
         * @param {UpdateOrderStatusRequest} updateOrderStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSalesOrderStatus(accountId: string, orderId: string, updateOrderStatusRequest: UpdateOrderStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateSalesOrderStatus(accountId, orderId, updateOrderStatusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SalesApi - interface
 */
export interface SalesApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {CreateSalesOrderRequest} createSalesOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSalesOrder(accountId: string, createSalesOrderRequest: CreateSalesOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrder>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrderDetailDto>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} [customerId] 
     * @param {string} [status] 
     * @param {string} [search] 
     * @param {string} [filter] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSalesOrders(accountId: string, customerId?: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): AxiosPromise<PagedResultOfSalesOrderDto>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {UpdateSalesOrderRequest} updateSalesOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSalesOrder(accountId: string, orderId: string, updateSalesOrderRequest: UpdateSalesOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<SalesOrder>;

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {UpdateOrderStatusRequest} updateOrderStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSalesOrderStatus(accountId: string, orderId: string, updateOrderStatusRequest: UpdateOrderStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * SalesApi - object-oriented interface
 */
export class SalesApi extends BaseAPI implements SalesApiInterface {
    /**
     * 
     * @param {string} accountId 
     * @param {CreateSalesOrderRequest} createSalesOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSalesOrder(accountId: string, createSalesOrderRequest: CreateSalesOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).createSalesOrder(accountId, createSalesOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).deleteSalesOrder(accountId, orderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSalesOrder(accountId: string, orderId: string, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).getSalesOrder(accountId, orderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} [customerId] 
     * @param {string} [status] 
     * @param {string} [search] 
     * @param {string} [filter] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSalesOrders(accountId: string, customerId?: string, status?: string, search?: string, filter?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).listSalesOrders(accountId, customerId, status, search, filter, page, pageSize, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {UpdateSalesOrderRequest} updateSalesOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSalesOrder(accountId: string, orderId: string, updateSalesOrderRequest: UpdateSalesOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).updateSalesOrder(accountId, orderId, updateSalesOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} accountId 
     * @param {string} orderId 
     * @param {UpdateOrderStatusRequest} updateOrderStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSalesOrderStatus(accountId: string, orderId: string, updateOrderStatusRequest: UpdateOrderStatusRequest, options?: RawAxiosRequestConfig) {
        return SalesApiFp(this.configuration).updateSalesOrderStatus(accountId, orderId, updateOrderStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



